<!DOCTYPE html>
<html>
<head>
  <style>
    .left {
        width: 50%;
        height: 100%;
        background-color: red;
        float: left;
    }

    .center {
        width: 50%;
        height: 100%;
        background-color: white;
        float: left;
    }

    .right {
        width: 50%;
        height: 100%;
        background-color: blue;
        float: left;
    }
  </style>
</head>
<body>
  <div class="left"></div>
  <div class="center"></div>
  <div class="right"></div>
</body>
</html>